### ISSUE TITLE
Pequena correção no Tutorial

### ISSUE THREAD

**Issue by DATAUNIRIO** [silvadenisson/electionsBR#10]
Parabéns pelo pacote do R. Uso o pacote em quase todas as aulas de Estatística para Ciência Política.
 Sugiro fazer uma pequena correção no Tutorial disponível no site:
http://fmeireles.com/blog/rstats/electionsbr-uma-nova-versao

O Tutorial está com a UF em caixa alta e a função do R esta com a uf em caixa baixa (segmento do tutorial de filiacao individuais). Envio o registro.

# Baixa dados de filiacao individuais do PT no estado de Sao Paulo
> x <- voter_affiliation(party = "PT", **UF** =** "SP", ascii = TRUE)
Error in voter_affiliation(party = "PT", **UF** = "SP", ascii = TRUE) :   unused argument (UF = "SP")

> x <- voter_affiliation(party = "PT", ascii = TRUE) 
Error in tolower(uf) : argument "uf" is missing, with no default

x <- voter_affiliation(party = "PT", **uf** = "SP", ascii = TRUE)
trying URL 'http://agencia.tse.jus.br/estatistica/sead/eleitorado/filiados/uf/filiados_pt_sp.zip'

**Comment by silvadenisson** [comment]
Olá! é muito bom saber que nosso pacote está servindo como material didático.

obrigado pela dica. de fato o nome do parâmetro UF é uf.  o segundo erro da lista é pq não é possível usar essa função sem declarar qual uf ou uf's  serão acessadas, não deixamos essa opção.

**Comment by meirelesff** [comment]
Corrigido. Obrigado pela dica. Abs.
