### ISSUE TITLE
Erro no download dos dados

### ISSUE THREAD

**Issue by cndesantana** [silvadenisson/electionsBR#12]
Salve,

Parece que o TSE mudou a localizacao dos dados das eleicoes. Enderecos do tipo http://agencia.tse.jus.br/estatistica/sead/odsele/votacao_candidato_munzona/votacao_candidato_munzona_2014.zip nao estao mais acessiveis. Por isso as funcoes como vote_mun_zone_fed(year) nao funcionam mais.

**Comment by silvadenisson** [comment]
Salve,

obrigado pelo  aviso. Bom que esses dias estamos atualizando o pacote ai já vemos o ocorreu com essas urls.
