### ISSUE TITLE
Erro - eleições 2010

### ISSUE THREAD

**Issue by wandersont** [silvadenisson/electionsBR#13]
Quando eu chamo a função details_mun_zone_fed(2010) ele baixa os dados mas dá o seguinte erro:

Error in data.table::rbindlist(.) :
Item 29 has 1 columns, inconsistent with item 1 whish has 26 columns. If instead you need to fill missing columns, use set argument 'fill' to TRUE.

**Comment by silvadenisson** [comment]
Possivelmente o TSE mudou alguma coisa na base. Normalmente, depois de algum tempo eles voltam a base pra formatação anterior. Mas, também estamos trabalhando na atualização do pacote, se o erro persistir na próxima versão vai ser corrigido isso.

obrigado por nos avisar.

**Comment by wandersont** [comment]
UPDATE
O problema é que no zip dos dados de 2010 ele traz um arquivo com voto em trânsito, ainda que neste ano esse dado não esteja disponível. Por conta disso, o arquivo bem apenas com uma mensagem de erro, não dividido nas colunas, como todos os outros arquivos. Isso faz com que o parser dê erro ao tentar ler esse arquivo.

Uma ideia é restringir a uf ZZ da leitura de 2010 pra trás.

Abraços!

**Comment by silvadenisson** [comment]
Obrigado pela informação, assim, nos ajudou em muito para solucionar o problema quando formos trabalhar no pacote.

Abraços!

**Comment by silvadenisson** [comment]
Resolvido este problema de arquivos vazios.
