### ISSUE TITLE
Connection with server was reset

### ISSUE THREAD

**Issue by DSE28** [silvadenisson/electionsBR#14]
Opa,
Tudo bem? 
Ao chamar a função **_details_mun_fed(2014)_** ou _**vote_mun_zone_local(2016)**_, é retornado o seguinte erro:
_"trying URL 'http://agencia.tse.jus.br/estatistica/sead/odsele/detalhe_votacao_munzona/detalhe_votacao_munzona_2014.zip'
Error in download.file(., dados) : 
  cannot open URL 'http://agencia.tse.jus.br/estatistica/sead/odsele/detalhe_votacao_munzona/detalhe_votacao_munzona_2014.zip'
In addition: Warning message:
In download.file(., dados) :
  InternetOpenUrl failed: 'The connection with the server was reset'"_

**Comment by silvadenisson** [comment]
Opa,
esse  erro pode ser só um problema com servidor do TSE, que logo eles corrigem...  estamos trabalhando em nova versão do pacote... mas estamos esperando "normalizar" mais os serviço do TSE pq eles estão atualizando a plataforma deles e está instável.

**Comment by prikaiser** [comment]
Pelo GitHub deu certo.
Obrigada!!
