### ISSUE TITLE
Erro dados candidatos municipais 2016

### ISSUE THREAD

**Issue by jmartinezcorrea** [silvadenisson/electionsBR#15]
Tem algum erro para baixar os dados de 2016.

candidate_local(2016)
Processing the data...
Error in names(banco) <- c("DATA_GERACAO", "HORA_GERACAO", "ANO_ELEICAO",  : 
  'names' attribute [46] must be the same length as the vector [0]

obrigado

**Comment by silvadenisson** [comment]
Meu caro, é possível que na ultima atualizacao o tse tenha mudado a estrutura do banco de dados. ainda nao voltamos nesse ano, mas ja estamos trabalhando na atualizacao do pacote pra incluir os novos ajustes do tse, pra o ano corrente já houve inclusao de novas variaveis.

**Comment by silvadenisson** [comment]
Problema resolvido, o TSE inseriu pra 2016 arquivos csv, mudando o padrao dos outros que é txt... entao agora funcao identifica se é csv ou txt e faz a leitura correta.

**Comment by jmartinezcorrea** [comment]
excelente. muito obg!
