### ISSUE TITLE
Erro nos dados 'candidate_fed(2014)'

### ISSUE THREAD

**Issue by dlimasouza** [silvadenisson/electionsBR#16]
Olá! Estou encontrando erro no carregamento dos dados dos candidatos em quase todos os anos (curioso é que os dados de 2006 carregam normalmente)

```
cands2014 <- candidate_fed(2014)
trying URL 'http://agencia.tse.jus.br/estatistica/sead/odsele/consulta_cand/consulta_cand_2014.zip'
Content type 'application/zip' length 5578986 bytes (5.3 MB)
downloaded 5.3 MB

Processing the data...
Error in names(banco) <- c("DATA_GERACAO", "HORA_GERACAO", "ANO_ELEICAO",  : 
  'names' attribute [46] must be the same length as the vector [0]
```

PS: Parabéns pelo pacote, é muito útil e prático.

**Comment by silvadenisson** [comment]
Olá meu caro, isso foi devido as ultimas alterações do TSE. na proxima atualização que vamos lançar, isso vai está pronto pra trabalhar com esse problema. 

obrigado!
