### ISSUE TITLE
Eleições 2018

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [silvadenisson/electionsBR#17]
Usando o comando 
`e2018 <- details_mun_zone_fed(2018)`

Ele retorna um erro
> Error in test_fed_year(year) : 
> Invalid input. Please, check the documentation and try again.

Mas os dados de 2018 já se encontram disponíveis no site do TSE

**Comment by silvadenisson** [comment]
O TSE ainda não disponibilizou no repositório de dados que é a nossa fonte: http://www.tse.jus.br/eleicoes/estatisticas/repositorio-de-dados-eleitorais-1/repositorio-de-dados-eleitorais

**Comment by silvadenisson** [comment]
Mas o tse ainda não disponibilizou no repositório de dados que é a nossa fonte: http://www.tse.jus.br/eleicoes/estatisticas/repositorio-de-dados-eleitorais-1/repositorio-de-dados-eleitorais

**Comment by WilliamCunhaCardoso** [comment]
Ah sim. Desculpa o engano.
