### ISSUE TITLE
Dados 2018

### ISSUE THREAD

**Issue by analisemacro** [silvadenisson/electionsBR#18]
Olá, pessoal, boa noite.

Vocês têm previsão de colocar os dados da eleição desse ano no pacote?

Desde já agradeço.

Abs

**Comment by silvadenisson** [comment]
Olá, a versao do github já está preparada para quando o tse liberar... vi no facebook não lembro se no grupo Rprogramdores ou Metodos alguem falando que o tse ia liberar esse final de semana.

Abs

**Comment by theaiacademy** [comment]
@silvadenisson parabéns pelo trabalho!
acabei de baixar o pacote do CRAN mas na documentação ainda indica que so 1998, 2002, 2006, 2010 e 2014 estão suportados. 

vai ter uma nova versão com os dados 2018?

abs

**Comment by silvadenisson** [comment]
Olá.... 
O a versão do GitHub já está incluso 2018... mas atenção.... devido a alterações do TSE nos arquivos, ainda não tivemos tempo de checar tudo e fazer as devidas correções.

Abs

**Comment by theaiacademy** [comment]
Obrigado @silvadenisson 
parece que teve mudanças de algumas feature mesmo ...
Os scripts que nos usamos na versão 0.3.0 (do CRAN) vão ter que ser modificados para a versão 0.3.1 (do GitHub) 

so pra dar um exemplo: 
> Error in filter_impl(.data, quo) : 
>  Evaluation error: object 'DESCRICAO_CARGO' not found.

A documentação também parece existir ainda so para a 0.3.0 (http://electionsbr.com/reference/index.html)

Vocês tem alguma previsão se e quando vai ser atualizada?

muito obrigado

**Comment by steveofconnell** [comment]
Hello @silvadenisson  -- thank you for your work on this project and package. Is there any chance you have updated the package to include 2018 data? Thank you!

**Comment by silvadenisson** [comment]
> Hello @silvadenisson -- thank you for your work on this project and package. Is there any chance you have updated the package to include 2018 data? Thank you!

Hello! in the version of github already has 2018 included. but we are still working on the version that goes to the cran because the TSE has changed some files.
