### ISSUE TITLE
"legislative_state_vote" não reconhecida

### ISSUE THREAD

**Issue by danielduque** [silvadenisson/electionsBR#23]
Atualizei o pacote electionsbr para pegar os dados de 2018, no entanto, o R não está reconhecendo a função "legislative_state_vote". Segue a mensagem:

> library(electionsBR)
> 
> 
> depfed18 <- legislative_state_vote(year=2018)
Error in legislative_state_vote(year = 2018) : 
  could not find function "legislative_state_vote"

Desde já agradecido
Daniel Duque

**Comment by silvadenisson** [comment]
Oi meu caro,  houve um erro na hora de atualizar o site... mantemos no site essa funcao... mas ela e mais duas retiramos do pacote devido a constantes erros.

são elas:
president_state_vote()
legislative_mun_vote()
legislative_state_vote()


Abs.,
Denisson
