### ISSUE TITLE
Um erro: object 'vts_local' not found

### ISSUE THREAD

**Issue by alicezxu** [silvadenisson/electionsBR#24]
Boa noite! 

Eu encontrei o seguinte erro ao usar especificamente a função vote_section_local ():
Error in vote_section_local(2008) : object 'vts_local' not found

^Existe uma maneira de resolver esse erro?

Eu também tenho duas perguntas rápidas para quando você tiver a chance:
1) Qual é a diferença entre party_mun_zone_fed e vote_mun_zone_fed? Ambos parecem fornecer votos recebidos por cado partido em cada cidade / zona e ambos têm 76.049 observações para 2014, pelo que parece que são idênticas.
2) Existe uma função para obter votos para governador por partido? Parece que party_mun_zone_fed e vote_mun_zone_fed incluem apenas votos para presidente, mas não há equivalente para governador / deputado / senador federal, etc.

Muita obrigada antecipadamente por toda a sua ajuda!

electionsBR é tão útil - muita obrigada por este serviço!

**Comment by alicezxu** [comment]
Há também um erro relacionado com vote_section_fed (2014):

Error in attr(x, "names") <- as.character(value) : 
  'names' attribute [22] must be the same length as the vector [15]

**Comment by alian0209** [comment]
Quero uma ajuda, como faço para instalar? Achei bacana

**Comment by andradelucaz** [comment]
Bom dia Denisson, também estou com o mesmo problema na função vote_section_local
Error in vote_section_local(2016, uf = "MG") : 
  objeto 'vts_local' não encontrado

Poderia me orientar?
Obrigado

**Comment by meirelesff** [comment]
Implementamos uma série de bug fixes no pacote nos últimos meses, mas, mesmo assim, esse problema persiste. Precisaremos resolver o problema ainda.

**Comment by meirelesff** [comment]
Problema (a princípio) resolvido no último PR.
