### ISSUE TITLE
Dados candidaturas vice-prefeito e vice-governador

### ISSUE THREAD

**Issue by amrabelo** [silvadenisson/electionsBR#30]
É possível fazer download de dados das eleições  para os cargos de vice? (prefeito e governador, principalmente.

**Comment by meirelesff** [comment]
Esses dados, por padrão, vêm nas mesmas planilhas com os resultados gerais. Por conta disso, é necessário, primeiro, baixar os dados de um dado pleito para, aí sim, realizar um filtro com qualquer método.
