### ISSUE TITLE
Função vote_mun_zone_fed e votos para as eleições presidenciais

### ISSUE THREAD

**Issue by igorlaltuf** [silvadenisson/electionsBR#42]
Eu tentei baixar os dados dos votos das eleições presidenciais de 2014 e 2018 com a função vote_mun_zone_fed, porém os dados retornados pela função foram apenas para os cargos de Governador, Senador, Deputado Federal e Deputado Estadual.

Vocês saberiam me dizer o porquê? 

```
mun_2014 <- vote_mun_zone_fed(2014, uf = 'RJ')
unique(mun_2014$DESCRICAO_CARGO)

mun_2018 <- vote_mun_zone_fed(2018, uf = 'RJ')
unique(mun_2018$DESCRICAO_CARGO)
```

**Comment by silvadenisson** [comment]
Voce precisa colocar o argumento da função br_archive para TRUE, que por padrão é FALSE

**Comment by igorlaltuf** [comment]
@silvadenisson muito obrigado.

Funcionou depois que coloquei o argumento que você indicou e não especifiquei o argumento "uf":

```
mun <- vote_mun_zone_fed(2018, br_archive = T)
```
