### ISSUE TITLE
Lista de nomes de zonas eleitorais?

### ISSUE THREAD

**Issue by sillasgonzaga** [silvadenisson/electionsBR#5]
Estou trabalhando com os dados de Boletim de Urna baixados diretamente do TSE e notei que há um campo com o código da zona eleitoral, mas não há algum com informações sobre a zona, como endereço e bairro. Tal lista existe?

**Comment by flaviobarros** [comment]
@sillasgonzaga essa informação existe. Provavelmente você deve estar tentando fazer mapinhas como eu ;-). Eu fui no site do TSE de SP e eles tem essa informação aqui: http://www.tre-sp.jus.br/eleitor/titulo-e-local-de-votacao/consulta-por-estado

Eu ainda não tive tempo de processar isso mas se você o fizer eu sugiro que você compartilhe aqui. Uma sugestão para um pull request era incluir isso como um data.frame de dados do pacote.

**Comment by sillasgonzaga** [comment]
@flaviobarros 

Na verdade minha intenção (a priori) não é fazer um mapa e sim estratificar os resultados dos candidatos por bairro. Este site é do TRE-SP, será que não tem uma lista unificada de todos os estados?

O site do TRE-SE (meu estado), por exemplo, não tem essa informação: http://www.tre-se.jus.br/eleitor/titulo-e-local-de-votacao/consulta-por-nome

**Comment by flaviobarros** [comment]
@sillasgonzaga então, eu consegui essa informação por aquela solicitação de informações do cidadão. No meu entendimento eles devem ter sim. Acho que temos que pedir no TSE direto.

**Comment by sillasgonzaga** [comment]
Faz sentido. Vou abrir um requerimento pela LAI.

**Comment by sillasgonzaga** [comment]
Resolvi a issue mandando um e-mail para o pessoal de estatística do TSE e eles gentilmente me responderam. [Link](https://drive.google.com/open?id=0B85iHUpDSZB5elVFd2R1XzAzX1U) para endereços das seções eleitorais.

**Comment by flaviobarros** [comment]
Boa GAROTO! Muito bom. Acho que estes dados bem poderiam fazer parte do pacote no futuro.
