### ISSUE TITLE
Incluir dados dos locais de votação

### ISSUE THREAD

**Issue by flaviobarros** [silvadenisson/electionsBR#7]
No #5 foi levantada a questão sobre informações sobre os locais de votação. Uma vez que o TSE disponibilizou os dados, seria interessante incluir esse dataset no próprio pacote, em uma pasta data/.

**Comment by sillasgonzaga** [comment]
Flávio, a planilha cedida tem 28MB. Como poderíamos fazer para não deixar o pacote pesado? Pensei em algo como criar funções de download de dados de um estado/cidade em específico.

**Comment by silvadenisson** [comment]
Acho essa solução bem interessante, esse arquivo tem 28MB em RDA? se for fica pesado de fato, ai poderíamos ver um local para hospedar-la e colocar uma função para fazer download dela no pacote. mas se esse tamanho for entrou formato acho que quando transformar para RDA vai fica bem pequena, assim, dar para incluir direto no pacote.

**Comment by meirelesff** [comment]
Mesmo que fosse possível comprimir pra menos de 5mb, o limite do CRAN, ainda tem outro problema: esses locais de votação mudam entre eleições. Hospedando os dados em algum lugar ou colocando eles no pacote, teríamos que atualizar os locais a cada eleição. Considerado isso tudo, ainda tem outro problema, esse o que eu acho o mais importante: esses dados não estão no repositório do TSE, que é o local de onde o pacote retira os dados eleitorais e a documentação das informações. Já tinham nos sugerido incluir dados do IBGE e outros, mas, pela mesma razão, preferimos manter o foco no repositório.

**Comment by sillasgonzaga** [comment]
Mas só temos eleições a cada 2 anos. Não seria um problema atualizar os dados das seções a cada  anos, até porque seu pacote sofrerá outras atualizações nesse intervalo de tempo.

Analisar os votos por bairro é um recurso muito importante para o pacote, acredito que valha a pena o esforço.

Sigo com minha sugestão. Eu sugiro até criar um repo no Github apenas para hospedar os dados (pode ser um para cada estado) e criar uma função do tipo `baixar_zonas_eleitorais(estado = "SP")` para obter os dados.

Dados do IBGE eu concordo que sejam um exagero.

**Comment by silvadenisson** [comment]
Sillas, com sugestão a sua sugestão de colocar esses dados em um repositório do github eu concordo.

**Comment by meirelesff** [comment]
Acho que um repo é uma solução boa mesmo, Sillas. Mas, supondo que criássemos um repo pra esses dados, como faríamos a documentação dele? O TSE te enviou algum material?

**Comment by sillasgonzaga** [comment]
Não @meirelesff , apenas a planilha.

Acredito que você pelo e-mail estatistica@tse.jus.br você consiga. Quem me passou a planilha foi a Érica ( erika.cardoso at tse.jus.br )
