### ISSUE TITLE
Vote by electoral section?

### ISSUE THREAD

**Issue by mochi-13** [silvadenisson/electionsBR#9]
I'm wondering if it's possible to get the data on votes by electoral section?

This is a wonderful tool, thank you very much for your contribution!

**Comment by meirelesff** [comment]
The package doesn't have a function to get this kind of data, although our code can be easily adapted to write one. Actually, we didn't include such a function in the package on purpuse to avoid users complains as the files for electoral results by section are really large. In case you do need to get this data, I think you're probably better of by creating a web crawling to download all the files and then loading one by one (maybe with a loop or with sapply). Hope this helps.

**Comment by mochi-13** [comment]
No worries, thanks for the clarification!

On Sat, Apr 22, 2017 at 7:38 PM, Fernando Meireles <notifications@github.com

**Comment by meirelesff** [comment]
As a late response, in this version we're working on we'll introduce a function to extract electoral results by voting sections -- one state at a time, at least.

**Comment by mochi-13** [comment]
Wonderful news!
